version: '2.1'
 
services:
  proxy:
    image: 'bahmni/proxy:${PROXY_IMAGE_TAG:?}'
    ports:
      - '80:80'
      - '443:443'
  
  openmrsdb:
    restart: "always"
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"
   # volumes:
   #   - openmrsdb-data:/var/lib/mysql
 
  openmrs:
    restart: "always"
    image: openmrs/openmrs-distro-platform:2.5.4
    depends_on:
      - openmrsdb
    ports:
      - "8080:8080"
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: openmrsdb
      DB_USERNAME: ${MYSQL_USER:-openmrs}
      DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'false'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - ${BAHMNI_CONFIG_PATH:?}/docker/masterdata/modules/:/usr/local/tomcat/.OpenMRS/modules/ 
      - ${BAHMNI_CONFIG_PATH:?}/masterdata/configuration/:/usr/local/tomcat/.OpenMRS/configuration/
 

