name: Build and Publish OpenMRS Clinic Config DB
on:
  push:
    branches:
      - main
      - 'release-*'
      - BAH-2668
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths: 
      - package/docker/resources/omrs*.gz
      - package/docker/resources/configuration_checksums.zip
      - package/docker/configdb.Dockerfile
  workflow_dispatch:
    
jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Decompress Files
        run: |
          gunzip package/docker/resources/omrs*.gz
          unzip package/docker/resources/configuration_checksums.zip -d package/docker/resources/
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: package/docker/configdb.Dockerfile
          push: true
          tags: bahmni/openmrs-db:${{env.ARTIFACT_VERSION}},bahmni/openmrs-db:clinic-config
